### ISSUE TITLE
RFE: install DCO checker

### ISSUE THREAD

**Issue by xosevp** [opensvc/multipath-tools#21]
https://github.com/apps/dco
https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/

**Comment by mwilck** [comment]
Do we want to enforce DCO?

This would affect mostly my own commits, because so far I added the s-o-b in the `git format-patch` step before posting to `dm-devel` rather than while committing, and therefore my s-o-b is missing on the commit message of basically all my contributions in the past in this repository (while it's present on the `dm-devel` posts).

I guess I'll change my habits and start using `git commit --signoff`. Wrt enforcing it for everyone, I have no strong opinion. Over the last months, all commits that came in via `dm-devel` and were not authored by myself have correct  DCO anyway. #19 is an exception (note that I had asked the author to submit to dm-devel and @cvaroqui  decided to merge this directly).

**Comment by bmarzins** [comment]
I'm not sure it gets us much.  There are very few patches that get posted by someone other than their author. Also, there are not a large number of authors for this project. It's not a sexy project that people really want to be a contributor for, so it seems less likely that someone will post code that they don't have the right to. The benefit doesn't seem worth any additional work, but it doesn't add any work for me, so I don't care one way or the other.

**Comment by xosevp** [comment]
A tip, the fastest way to sign **all** patches is to add to  `~/.gitconfig` :
```
[format]
	signoff 		= true
```
I am going to close it.

**Comment by xosevp** [comment]
z
